import { createElement, type ReactElement } from 'react';
import {
  Archive,
  ArrowLeft,
  ArrowRight,
  Bot,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CirclePlay,
  ExternalLink,
  FoldVertical,
  Folder,
  FolderOpen,
  FolderX,
  GitMerge,
  ListFilter,
  MessageSquarePlus,
  OctagonX,
  PanelRight,
  Pencil,
  Play,
  Plus,
  Power,
  PowerOff,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  Save,
  SendHorizontal,
  Sparkles,
  Square,
  SquareTerminal,
  Trash2,
  X,
  type LucideIcon,
} from 'lucide-react';

/**
 * The app's icon vocabulary: one verb, one icon. A call site names the verb
 * and never imports lucide. See DESIGN.md § Icons for the hand-drawn exceptions.
 */
const ICONS = {
  approve: Check,
  archive: Archive,
  back: ArrowLeft,
  close: X,
  closeWorktree: FolderX,
  comment: MessageSquarePlus,
  compact: FoldVertical,
  delete: Trash2,
  decline: X,
  deny: X,
  dismiss: X,
  disclose: ChevronDown,
  edit: Pencil,
  envRestart: RotateCw,
  envStart: Power,
  envStop: PowerOff,
  external: ExternalLink,
  filter: ListFilter,
  folder: Folder,
  folderOpen: FolderOpen,
  freeAgent: Bot,
  launch: Rocket,
  merge: GitMerge,
  new: Plus,
  next: ArrowRight,
  openInPanel: PanelRight,
  pageNext: ChevronRight,
  pagePrevious: ChevronLeft,
  refresh: RotateCw,
  resolve: CheckCheck,
  resume: CirclePlay,
  retry: RotateCcw,
  save: Save,
  send: SendHorizontal,
  start: Play,
  stop: Square,
  suggest: Sparkles,
  sync: RefreshCw,
  terminal: SquareTerminal,
  terminate: OctagonX,
} satisfies Record<string, LucideIcon>;

export type ActionVerb = keyof typeof ICONS;

/** The icon for `verb`. `className` sizes an icon outside a button, e.g. in a link. */
export function actionIcon(verb: ActionVerb, className?: string): ReactElement {
  return createElement(ICONS[verb], { className });
}
